"""measured.py - diagrams drawn from REAL simulation and synthesis data.

Every picture here is regenerated by running the Verilog, so if the
hardware changes, the pictures change with it.
"""
import csv
import os
import re
import subprocess
from svg import Svg, C

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = None
BUILD = os.path.join(ROOT, "build", "diagrams")


def P(name):
    return f"{OUT}/{name}"


def sh(cmd, cwd=None):
    return subprocess.run(cmd, shell=True, cwd=cwd or ROOT, check=True,
                          capture_output=True, text=True).stdout

# ------------------------------------------------------------------ VCD

def read_vcd(path, wanted):
    """Minimal VCD reader -> {name: [(time, value_int)]} for names ending in `wanted`."""
    ids, scope, sig = {}, [], {}
    with open(path) as fh:
        t = 0
        header = True
        for line in fh:
            tok = line.split()
            if not tok:
                continue
            if header:
                if tok[0] == "$scope":
                    scope.append(tok[2])
                elif tok[0] == "$upscope":
                    scope.pop()
                elif tok[0] == "$var":
                    name = ".".join(scope + [tok[4]])
                    for w in wanted:
                        if name.endswith(w) and w not in sig:
                            ids.setdefault(tok[3], []).append(w)
                            sig[w] = []
                elif tok[0] == "$enddefinitions":
                    header = False
                continue
            if tok[0][0] == "#":
                t = int(tok[0][1:])
            elif tok[0][0] in "b":
                v, i = tok[0][1:], tok[1]
                for w in ids.get(i, []):
                    sig[w].append((t, int(v.replace("x", "0").replace("z", "0"), 2)))
            elif tok[0][0] in "01xz" and len(tok) == 1:
                v, i = tok[0][0], tok[0][1:]
                for w in ids.get(i, []):
                    sig[w].append((t, 1 if v == "1" else 0))
    return sig


def sample(changes, times):
    out, k, cur = [], 0, 0
    for t in times:
        while k < len(changes) and changes[k][0] <= t:
            cur = changes[k][1]
            k += 1
        out.append(cur)
    return out


def simulate(version, demo="mlp"):
    os.makedirs(BUILD, exist_ok=True)
    vvp = os.path.join(BUILD, f"{version}.vvp")
    sh(f"iverilog -g2012 -o {vvp} tb/tb_tpu_top.v rtl/common/*.v rtl/{version}/*.v")
    bdir = os.path.join(BUILD, f"run_{version}_{demo}")
    os.makedirs(os.path.join(bdir, "build"), exist_ok=True)
    sh(f"python3 {ROOT}/tools/golden_model.py --demo {demo} --seed 1 --out build", cwd=bdir)
    log = sh(f"vvp -n {vvp}", cwd=bdir)
    assert "PASS" in log, log
    cyc = int(re.search(r"finished in (\d+)", log).group(1))
    return os.path.join(bdir, "build", "tpu.vcd"), cyc


SIGS = ["tb_tpu_top.rst", "dut.in_valid", "u_ctrl.state", "u_ctrl.pc", "dut.w_load", "dut.a_skewed",
        "u_acc.wr_en", "u_acc.wr_addr", "dut.ub_wr_en", "u_ctrl.done"]


def cycle_samples(vcd):
    sig = read_vcd(vcd, SIGS + ["tb_tpu_top.clk"])
    rises = [t for t, v in sig["tb_tpu_top.clk"] if v == 1]
    rst = sample(sig["tb_tpu_top.rst"], rises)
    start = next(i for i, r in enumerate(rst) if r == 0)
    times = [t - 1 for t in rises[start:]]          # value held just before each edge
    data = {k: sample(sig[k], times) for k in SIGS if k in sig}
    return data

# ------------------------------------------------------------------ waveform

def waveform():
    vcd, _ = simulate("v1_simple")
    d = cycle_samples(vcd)
    c0, c1 = 0, 30
    names = ["FETCH", "DECODE", "LDW", "MMUL", "ACT", "HALT"]
    rows = [("state", "u_ctrl.state", "bus", C["ctl"], lambda v: names[v]),
            ("pc", "u_ctrl.pc", "bus", C["ctl"], str),
            ("w_load", "dut.w_load", "bit", C["wt"], None),
            ("row 0 input", "dut.a_skewed", "lane0", C["act"], None),
            ("row 1 input", "dut.a_skewed", "lane1", C["act"], None),
            ("row 2 input", "dut.a_skewed", "lane2", C["act"], None),
            ("row 3 input", "dut.a_skewed", "lane3", C["act"], None),
            ("result valid", "u_acc.wr_en", "bit", C["out"], None),
            ("acc address", "u_acc.wr_addr", "bus_when_valid", C["ps"], str)]
    cw, x0, top, rh = 27, 150, 130, 44
    W = x0 + (c1 - c0) * cw + 30
    s = Svg(W, top + rh * len(rows) + 70, "A real waveform: LDW then MMUL (from the Verilog simulation)",
            ["Rendered from build/tpu.vcd of rtl/v1_simple. Watch the staircase in the row inputs, and the 7-cycle wait before",
             "results appear. Numbers in the row inputs are the int8 values entering the array."])
    for c in range(c0, c1 + 1):
        x = x0 + (c - c0) * cw
        s.line(x, top - 10, x, top + rh * len(rows) - 8, C["line"], 1, dash="2 4")
        if c % 5 == 0 and c < c1:
            s.text(x + 2, top - 16, f"{c}", 11, C["muted"])
    s.text(x0 - 6, top - 16, "cycle", 11, C["muted"], anchor="end")
    for r, (lab, key, mode, col, fmt) in enumerate(rows):
        y = top + r * rh
        s.text(x0 - 12, y + 20, lab, 13, col, 700, "end")
        vals = d[key][c0:c1]
        if mode.startswith("lane"):
            ln = int(mode[4:])
            vals = [((v >> (8 * ln)) & 255) for v in vals]
            vals = [v - 256 if v > 127 else v for v in vals]
            iv = d["dut.in_valid"]
            ok = [c0 + i - ln >= 0 and iv[c0 + i - ln] for i in range(len(vals))]
            for i, v in enumerate(vals):
                if ok[i]:
                    x = x0 + i * cw
                    s.rect(x + 1, y + 4, cw - 2, 26, C["act_bg"], col, 1.2, 4)
                    s.text(x + cw / 2, y + 22, str(v), 10, C["act_dk"], 700, "middle")
            continue
        if mode == "bit":
            pts = []
            for i, v in enumerate(vals):
                yy = y + (6 if v else 30)
                pts += [(x0 + i * cw, yy), (x0 + (i + 1) * cw, yy)]
            s.path("M" + " L".join(f"{a:.0f} {b:.0f}" for a, b in pts), col, 2.5)
            continue
        valid = d["u_acc.wr_en"][c0:c1]
        i = 0
        while i < len(vals):
            j = i
            while j < len(vals) and vals[j] == vals[i] and (mode != "bus_when_valid" or valid[j] == valid[i]):
                j += 1
                if mode == "bus_when_valid":
                    break
            if mode != "bus_when_valid" or valid[i]:
                x, w = x0 + i * cw, (j - i) * cw
                s.add(f'<path d="M{x + 3} {y + 4} L{x + w - 3} {y + 4} L{x + w} {y + 17} L{x + w - 3} {y + 30} '
                      f'L{x + 3} {y + 30} L{x} {y + 17} Z" fill="{C["white"]}" stroke="{col}" stroke-width="1.5"/>')
                if w >= 26:
                    s.text(x + w / 2, y + 22, fmt(vals[i]), 10 if w < 60 else 11, col, 700, "middle")
            i = j
    iv = d["dut.in_valid"][c0:c1]
    wv = d["u_acc.wr_en"][c0:c1]
    if 1 in iv and 1 in wv:
        a, b = iv.index(1), wv.index(1)
        yy = top + rh * len(rows) + 16
        s.line(x0 + a * cw, yy, x0 + b * cw, yy, C["ps"], 2.5, True, start_arrow=True)
        s.text(x0 + (a + b) / 2 * cw, yy + 20, f"{b - a} cycles = 2N - 1 latency", 13, C["ps"], 700, "middle")
    s.save(P("waveform_ldw_mmul.svg"))

# ------------------------------------------------------------------ v1 vs v2 timeline

def gantt():
    runs = [(v, *simulate(v)) for v in ("v1_simple", "v2_pipelined")]
    prog = [l.split(";")[0].strip() for l in open(os.path.join(ROOT, "programs", "mlp_demo.asm")) if l.split(";")[0].strip()]
    maxc = max(c for _, _, c in runs) + 2
    cw, x0 = 9.5, 150
    s = Svg(int(x0 + maxc * cw + 40), 560, "v1 vs v2: the same program, overlapped",
            ["Both runs come straight from the Verilog (programs/mlp_demo.asm). Top bar: what the controller is doing.",
             "Bottom bar: when results land in the accumulators. v2 keeps working while results are still in flight."])
    kinds = {0: ("ctl", "fetch"), 1: ("ctl", "decode / stall"), 2: ("wt", "LDW"), 3: ("mxu", "MMUL"),
             4: ("out", "ACT"), 5: ("red", "HALT")}
    for r, (ver, vcd, cyc) in enumerate(runs):
        d = cycle_samples(vcd)
        st, pc, wr = d["u_ctrl.state"][:cyc], d["u_ctrl.pc"][:cyc], d["u_acc.wr_en"][:cyc]
        y = 170 + r * 170
        s.text(x0 - 14, y + 22, ver.replace("_", " "), 15, C["ink"], 700, "end")
        s.text(x0 - 14, y + 42, f"{cyc} cycles", 13, C["mxu"] if r else C["muted"], 700, "end")
        i = 0
        while i < cyc:
            j = i
            while j < cyc and st[j] == st[i] and pc[j] == pc[i]:
                j += 1
            k, lab = kinds.get(st[i], ("ctl", "?"))
            s.rect(x0 + i * cw, y, (j - i) * cw - 1, 36, C[f"{k}_bg"], C[k], 1.2, 3)
            if st[i] in (2, 3, 4) and (j - i) * cw > 34:
                s.text(x0 + (i + j) / 2 * cw, y + 23, lab, 11, C.get(f"{k}_dk", C["ink"]), 700, "middle")
            i = j
        s.text(x0 - 14, y + 78, "results", 12, C["ps"], 600, "end")
        for i in range(cyc):
            if wr[i]:
                s.rect(x0 + i * cw, y + 62, cw - 1, 24, C["ps"], None, 0, 2)
        s.line(x0 + cyc * cw, y - 10, x0 + cyc * cw, y + 100, C["red"], 2, dash="4 3")
    for c in range(0, maxc, 10):
        s.text(x0 + c * cw, 520, str(c), 11, C["muted"], anchor="middle")
    s.text(x0, 545, "clock cycle", 12, C["muted"])
    s.legend(x0 + maxc * cw - 170, 70, [(C["wt"], "LDW"), (C["mxu"], "MMUL"), (C["out"], "ACT"), (C["ps"], "result written")], 170)
    s.save(P("v1_vs_v2_timeline.svg"))
    return {v: c for v, _, c in runs}

# ------------------------------------------------------------------ utilization

def utilization():
    """Run LDW + MMUL(rows=M) + HALT on both versions for many M."""
    os.makedirs(BUILD, exist_ok=True)
    res = {}
    for ver in ("v1_simple", "v2_pipelined"):
        vvp = os.path.join(BUILD, f"{ver}.vvp")
        sh(f"iverilog -g2012 -o {vvp} tb/tb_tpu_top.v rtl/common/*.v rtl/{ver}/*.v")
        bdir = os.path.join(BUILD, f"util_{ver}")
        os.makedirs(os.path.join(bdir, "build"), exist_ok=True)
        pts = []
        for m in [1, 2, 4, 8, 16, 32, 64, 128, 255]:
            code = (f"import sys; sys.path.insert(0,'{ROOT}/tools'); import golden_model as g, random;"
                    f"r=random.Random(1); prog=[0x10000000, 0x20000000|({m}<<12), 0x10400000, 0x20000001|({m}<<12), 0x10800000, 0x20000001|({m}<<12), 0x10C00000, 0x20000001|({m}<<12), 0xF0000000];"
                    f"g.run_and_write('build', prog, g.rand_mat(r,256,4,-128,127), g.rand_mat(r,256,4,-128,127))")
            sh(f'python3 -c "{code}"', cwd=bdir)
            log = sh(f"vvp -n {vvp} +novcd", cwd=bdir)
            assert "PASS" in log
            cyc = int(re.search(r"finished in (\d+)", log).group(1))
            pts.append((m, 4 * 16 * m / (16 * cyc)))
        res[ver] = pts
    s = Svg(980, 560, "Utilization climbs with batch size (measured on the RTL)",
            ["Program: 4 weight tiles, each LDW + MMUL of M vectors, accumulated (a K = 16 matrix multiply). Every point is a real",
             "Verilog run. Utilization = useful MACs ÷ (16 PEs x cycles). Dashed: perfect-overlap limit 4M / (4M + 2N - 2)."])
    x0, x1, y0, y1 = 110, 920, 500, 120
    import math
    X = lambda m: x0 + math.log2(m) / 8 * (x1 - x0)
    Y = lambda u: y0 - u * (y0 - y1)
    for u in [0, 0.25, 0.5, 0.75, 1.0]:
        s.line(x0, Y(u), x1, Y(u), C["line"], 1, dash="3 4")
        s.text(x0 - 10, Y(u) + 4, f"{int(u * 100)}%", 12, C["muted"], anchor="end")
    for m in [1, 2, 4, 8, 16, 32, 64, 128, 256]:
        s.text(X(m), y0 + 20, str(m), 12, C["muted"], anchor="middle")
    s.text((x0 + x1) / 2, y0 + 44, "batch size M (vectors per MMUL)", 13, C["ink"], 600, "middle")
    s.path("M" + " L".join(f"{X(m):.1f} {Y(4 * m / (4 * m + 6)):.1f}" for m in [2 ** (k / 8) for k in range(0, 65)]),
           C["faint"], 2.5, dash="7 5")
    for ver, col in (("v1_simple", C["wt"]), ("v2_pipelined", C["mxu"])):
        pts = res[ver]
        s.path("M" + " L".join(f"{X(m):.1f} {Y(u):.1f}" for m, u in pts), col, 3)
        for m, u in pts:
            s.circle(X(m), Y(u), 5, col, C["white"], 2)
        m, u = pts[-1]
    for k, (ver, col) in enumerate((("v1_simple", C["wt"]), ("v2_pipelined", C["mxu"]))):
        for m, u in res[ver]:
            if m in (4, 16):
                s.text(X(m) + (-10 if k == 0 else 10), Y(u) + (18 if k == 0 else -10), f"{u * 100:.0f}%", 13, col, 700,
                       "end" if k == 0 else "start")
    s.legend(140, 130, [(C["wt"], "v1_simple (waits for results)"), (C["mxu"], "v2_pipelined (overlaps)"),
                        (C["faint"], "perfect-overlap limit")], 260)
    s.save(P("utilization_vs_batch.svg"))
    return res

# ------------------------------------------------------------------ synthesis

def synth_chart():
    path = os.path.join(ROOT, "data", "synth.csv")
    rows = [r for r in csv.DictReader(open(path)) if r["area_um2"]]
    if not rows:
        print("  (no sky130 area data; run make synth with the PDK installed)")
        return
    s = Svg(980, 520, "How big is it? Systolic array area in SkyWater 130 nm",
            ["Synthesized with Yosys onto sky130_fd_sc_hd standard cells (tools/synth_report.sh, data/synth.csv).",
             "Area grows with N² because the PE count does. v2's shadow registers cost about 8 % more area."])
    arr = [r for r in rows if r["design"].startswith("systolic")]
    Ns = sorted({int(r["N"]) for r in arr})
    mx = max(float(r["area_um2"]) for r in arr)
    x0, y0, y1 = 140, 450, 130
    for i, n in enumerate(Ns):
        for j, ver in enumerate(("v1_simple", "v2_pipelined")):
            r = next(r for r in arr if int(r["N"]) == n and r["version"] == ver)
            a = float(r["area_um2"])
            h = a / mx * (y0 - y1)
            x = x0 + i * 250 + j * 80
            col = C["wt"] if j == 0 else C["mxu"]
            s.rect(x, y0 - h, 70, h, col, None, 0, 4, opacity=0.9)
            s.text(x + 35, y0 - h - 26, f"{a / 1e6:.3f} mm²", 12, col, 700, "middle")
            s.text(x + 35, y0 - h - 10, f"{int(r['cells']):,} cells", 11, C["muted"], anchor="middle")
        s.text(x0 + i * 250 + 75, y0 + 24, f"N = {n}  ({n * n} PEs)", 14, C["ink"], 700, "middle")
    pe = next((r for r in rows if r["design"] == "pe"), None)
    if pe:
        a = float(pe["area_um2"])
        tx = 140
        s.text(tx, 180, f"one PE ≈ {a:,.0f} µm²", 15, C["ink"], 700)
        s.text(tx, 204, f"x 65,536 PEs (TPU v1 size)", 13, C["muted"])
        s.text(tx, 224, f"≈ {a * 65536 / 1e6:,.0f} mm² at 130 nm", 13, C["red"], 700)
        s.text(tx, 248, "TPU v1's whole die, at 28 nm, was", 13, C["muted"])
        s.text(tx, 268, "under 331 mm². Smaller transistors", 13, C["muted"])
        s.text(tx, 288, "are the other half of the story.", 13, C["muted"])
    s.legend(400, 150, [(C["wt"], "v1_simple"), (C["mxu"], "v2_pipelined")], 160)
    s.save(P("synth_area.svg"))


ALL = [waveform, gantt, utilization, synth_chart]
